locals {
 cluster_name = "${var.project}-${var.stage}-cluster"
 security_group_name = "${var.project}-${var.stage}-sg"
 autoscaling_group_name = "${var.project}-${var.stage}-ag"
 service_name = "${var.project}-${var.stage}-service"
 instance_name = "${var.project}-${var.stage}-instance"
 cloudwatch_name = "${var.project}-${var.stage}-cloudwatch"
 task_name = "${var.project}-${var.stage}"
 loadbalancer_sg_name = "${var.project}-${var.stage}-LoadBalancer-sg"
 loadbalancer_name = "${var.project}-${var.stage}-LoadBalancer"
 target_group_name = "${var.project}-${var.stage}-tg"
 autoscaling_policy_up = "${var.project}-${var.stage}-ScaleUp"
 autoscaling_policy_down = "${var.project}-${var.stage}-ScaleDown"
 alarm_name_hight = "${var.project}-${var.stage}-RequestCountPerTarget-High"
 alarm_name_low = "${var.project}-${var.stage}-RequestCountPerTarget-Low"
 vpc_name = "${var.project}-${var.stage}-vpc"
 ecs_service_role_name = "${var.project}-${var.stage}-ecs-role"
 ecs_for_ec2_service_role_name = "${var.project}-${var.stage}-ec2-role"
}