locals {
 cluster_name = "${var.project}-${var.environment}-cluster"
 security_group_name = "${var.project}-${var.environment}-sg"
 autoscaling_group_name = "${var.project}-${var.environment}-ag"
 service_name = "${var.project}-${var.environment}-service"
 instance_name = "${var.project}-${var.environment}-instance"
 cloudwatch_name = "${var.project}-${var.environment}-cloudwatch"
 task_name = "${var.project}-${var.environment}"
 loadbalancer_sg_name = "${var.project}-${var.environment}-LoadBalancer-sg"
 loadbalancer_name = "${var.project}-${var.environment}-LoadBalancer"
 target_group_name = "${var.project}-${var.environment}-tg"
 autoscaling_policy_up = "${var.project}-${var.environment}-ScaleUp"
 autoscaling_policy_down = "${var.project}-${var.environment}-ScaleDown"
 alarm_name_hight = "${var.project}-${var.environment}-RequestCountPerTarget-High"
 alarm_name_low = "${var.project}-${var.environment}-RequestCountPerTarget-Low"
 vpc_name = "${var.project}-${var.environment}-vpc"
 ecs_service_role_name = "${var.project}-${var.environment}-ecs-role"
 ecs_for_ec2_service_role_name = "${var.project}-${var.environment}-ec2-role"
}